{{distinguish|Zagat}}
{{Other uses|Zakat (disambiguation)}}
{{Use dmy dates|date=February 2011}}
{{Islam|practices}}
{{Aqidah|Five Pillars}}
[[File:Dinar Dirham Web.jpg|thumb|[[Silver]] or [[gold]] coinage are one way of granting zakat.]]
'''Zakat''' ({{lang-ar| زكاة}} ''zakāt'', "that which purifies",<ref name=fvbb1/> also '''Zakat al-mal''' {{lang|ar|زكاة ألمال}}, "zakat on wealth",<ref name="Life">{{cite web|url=http://www.lifeusa.org/site/PageServer?pagename=r_zakah|title=Zakat Al-Maal (Tithing)|last=|first=|date=|website=Life USA|publisher=|archive-url=https://web.archive.org/web/20161006205721/http://www.lifeusa.org/site/PageServer?pagename=r_zakah|archive-date=2016-10-06|accessdate=11 August 2016}}</ref> or "'''Zakah'''"<ref>{{Cite web|url=http://www.islam101.com/dawah/zakah.htm|title=Zakah|website=www.islam101.com|access-date=2017-04-20}}</ref>) is a form of [[alms-giving]] treated in [[Islam]] as a religious obligation or tax,<ref>{{cite journal |author= Salehi, M |year=2014 |title= A Study on the Influences of Islamic Values on Iranian Accounting Practice and Development |journal= Journal of Islamic Economics, Banking and Finance |volume= 10 |issue=2 |pages= 154–182 |quote=Zakat is a religious tax that every Muslim has to pay. |doi= 10.12816/0025175}}</ref><ref>{{cite journal |author= Lessy, Z |year=2009 |title= Zakat (alms-giving) management in Indonesia: Whose job should it be? |journal= La Riba Journal Ekonomi Islam |volume= 3 |issue=1 |quote= zakat is alms-giving and religiously obligatory tax.}}</ref> which, by [[Quran]]ic ranking, is next after prayer (''salat'') in importance.<ref>{{cite book |last= Hallaq |first= Wael |authorlink= Wael B. Hallaq |title = The impossible state: Islam, politics, and modernity's moral predicament | publisher = [[Columbia University Press]] | location = [[New York City|New York]] | year = 2013 | isbn = 9780231162562 | page = 123 }}</ref>

As one of the [[Five Pillars of Islam]], zakat is a religious obligation for all Muslims who meet the necessary criteria of wealth.<ref name=yaqaradxix/> It is not a charitable contribution,<ref name=AhmedGianci/> and is considered to be a tax, or obligatory alms.<ref name=tusi2010>Muḥammad ibn al-Ḥasan Ṭūsī (2010), ''Concise Description of Islamic Law and Legal Opinions'', ISBN 978-1904063292, pp. 131–135</ref><ref>{{cite journal| author= Hefner R.W. |year=2006 |title= Islamic economics and global capitalism |journal= Society |volume= 44 |issue=1 |pages= 16–22 |quote= Zakat is a tax levied on income and wealth for the purpose of their purification. |doi= 10.1007/bf02690463 }}</ref> The payment and disputes on zakat have played a major role in the history of Islam, notably during the [[Ridda wars]].<ref name=mbonner15/><ref>Shoufani, Elias (1973), ''Al-Riddah and the Muslim Conquest of Arabia'', University of Toronto Press, ISBN 978-0802019158</ref>{{page needed|date=April 2016}}

Zakat is based on income and the value of all of one's possessions.<ref>Décobert, C. (1991), ''Le mendiant et le combattant, L’institution de l’islam'', Paris: Editions du Seuil, pp. 238–240</ref><ref>Medani Ahmed and Sebastian Gianci, ''Zakat'', Encyclopedia of Taxation and Tax Policy, p. 479, quote: "As one of the Islam's five pillars, zakat becomes an obligation due when, over a lunar year, one controls a combination of income and wealth equal to or above [[Nisaab]]."</ref> It is customarily 2.5% (or 1/40th) of a Muslim's total savings and wealth above a minimum amount known as ''[[nisab]]'',<ref name=yaqaradawi/> but Islamic scholars differ on how much  nisab is and other aspects of zakat.<ref name=yaqaradawi/> The collected amount is paid first to zakat collectors, and then to poor Muslims, to new converts to Islam, to Islamic [[clergy]], and others.<ref name=naserg/><ref name=mariff/><ref name=mams/>

Today, in most Muslim-majority countries, zakat contributions are voluntary, while in a handful ([[Libya]], [[Malaysia]], [[Pakistan]], [[Saudi Arabia]], [[Sudan]], and [[Yemen]]), zakat is mandated and collected by the state.<ref name="Marty-1996-p.320"/><ref name=Hasan/>

[[Shias]], unlike [[Sunnis]], have traditionally regarded zakat as a private and voluntary decision, and they give zakat to [[imam]]-sponsored rather than state-sponsored collectors.<ref>{{cite book |author1= Jones, Owen Bennett |title= Pakistan: Eye of the Storm |date=2003 |publisher= Yale University Press |isbn= 978-0300101478 |pages=21–23 |edition= illustrated}}</ref><ref>{{cite book |author1= John, Wilson |editor1-last=John |editor1-first=Wilson |title= Pakistan: The Struggle Within |date=2009 |publisher= Pearson Education India |isbn= 978-8131725047 |page=105}}</ref><ref>{{cite book |author1= Kumaraswamy, P. R. |author2= Copland, Ian |editor1-last= Kumaraswamy |editor1-first=P.R. |editor2-last= Copland |editor2-first=Ian |title= South Asia: The Spectre of Terrorism |date=18 Oct 2013 |publisher= Routledge |isbn= 978-1317967736 |page=132}}</ref>

==Etymology==
Zakat literally means "that which purifies".<ref name=fvbb1>{{cite book |author= Benda-Beckmann, Franz von |title= Social security between past and future: Ambonese networks of care and support |publisher= LIT Verlag, Münster |year=2007 |isbn= 978-3-8258-0718-4 |page=167|url=https://books.google.com/books?id=fVw6QB-kTYwC&pg=PA167 |quote= ''Zakat'' literally means 'that which purifies'. It is a form of sacrifice which purifies worldly goods from their worldly and sometimes impure means of acquisition, and which, according to God's wish, must be channeled towards the community.}}</ref>
Zakat is considered a way to purify one's income and wealth from sometimes worldly, impure ways of acquisition.<ref name=fvbb1/><ref>Ridgeon, Lloyd (2003), ''Major World Religions: From Their Origins to the Present'', Routledge, ISBN 978-0415297967, pp. 258: "The Quranic term zakat came to signify a form of obligatory charity or alms tax that was seen as a means of purifying the believer's wealth."</ref><ref>{{cite journal |author1=Dean, H. |author2= Khan, Z. |lastauthoramp=yes |year=1998 |title= Islam: A challenge to welfare professionalism |journal= Journal of Interprofessional Care |volume= 12 |issue=4 |pages= 399–405 |quote= Zakat purifies the wealth of the individual |doi= 10.3109/13561829809024947}}</ref><ref>{{Cite quran|9|103|s=nosup}}</ref>
According to Sachiko Murata and [[William Chittick]], "Just as ablutions purify the body and [[Salah|salat]] purifies the soul (in Islam), so zakat purifies possessions and makes them pleasing to God."<ref>Murata, S. and Chittick, W. C. (1994), ''The vision of Islam'', IB Tauris, London, ISBN 978-1557785169, p. 16</ref><ref name=Heck />

It is sometimes referred to as ''Zakat al-mal''.<ref name="Life" />

==Doctrine==

===Quran===
The [[Quran]] discusses charity in many verses, some of which relate to zakat. The word zakat, with the meaning used in Islam now, is found in [[sura]]s: 7:156, 19:31, 19:55, 21:73, 23:4, 27:3, 30:39, 31:4 and 41:7.<ref>Yusuf al-Qaradawi (1999), Monzer Kahf (transl.), Fiqh az-Zakat, Dar al Taqwa, London, Volume 1, ISBN 978-967-5062-766, p. XL, "Qur'an used the word zakah, in the meaning known to Muslims now, as early as the beginning of the Makkan period. This is found in Suras: 7:156, 19:31 and 55, 21:72, 23:4, 27:7, 30:39, 31:3 and 41:7."</ref><ref>The English translation of these verses can be read here [http://www.usc.edu/org/cmje/religious-texts/quran/], University of Southern California</ref>
Zakat is found in the early [[Medinan sura]]s and described as obligatory for Muslims.<ref name=Heck>{{cite encyclopedia|last= Heck |first= Paul L. |editor-first= Jane Dammen |editor-last= McAuliffe |editor-link= Jane Dammen McAuliffe |encyclopedia= [[Encyclopaedia of the Qur'an]] |title= Taxation|year= 2006 |publisher= [[Brill Publishers]] |volume= vol. 5 |location= [[Leiden]] |isbn= 90-04-14743-8 }}</ref> It is given for the sake of salvation. Muslims believe those who give zakat can expect reward from God in the afterlife, while neglecting to give zakat can result in damnation. Zakat is considered part of the covenant between God and a Muslim.<ref name=Heck />

According to [[Yusuf al-Qaradawi]], verse 9.5 of the Quran<ref>{{cite quran|9|5|s=nosup}}</ref> makes zakat one of three prerequisites for pagans to become Muslims: "but if they repent, establish prayers, and practice zakat they are your brethren in faith".<ref name=yaqaradxix>Yusuf al-Qaradawi (1999), Monzer Kahf (transl.), Fiqh az-Zakat, Dar al Taqwa, London, Volume 1, ISBN 978-967-5062-766, p. XIX</ref>

The Quran also lists who should receive the benefits of zakat, discussed in more detail [[Zakāt#Distribution|below]].<ref name=Zysow/>

===Hadith===
Each of the most trusted [[hadith]] collections in Islam have a book dedicated to zakat. Sahih Bukhari's Book 24,<ref>[http://www.usc.edu/org/cmje/religious-texts/hadith/bukhari/024-sbt.php Obligatory Charity Tax (Zakat)], Sahih Bukhari, University of Southern California</ref> Sahih Muslim's Book 5,<ref>[http://www.usc.edu/org/cmje/religious-texts/hadith/muslim/005-smt.php The Book of Zakat (Kitab Al-Zakat)], Sahih Muslim, University of Southern California</ref> and Sunan Abu-Dawud's Book 9<ref>[http://www.usc.edu/org/cmje/religious-texts/hadith/abudawud/009-sat.php Zakat (Kitab Al-Zakat)], Sunan Abu-Dawood, University of Southern California</ref> discuss various aspects of zakat, including who must pay, how much, when and what. The 2.5% rate is also mentioned in the hadiths.<ref>{{hadith-usc|usc=yes|abudawud|9|1568}}</ref>

The hadiths admonish those who do not give the zakat. According to the hadith, refusal to pay or mockery of those who pay zakat is a sign of [[munafiq|hypocrisy]], and God will not accept the prayers of such people.<ref>{{hadith-usc|usc=yes|muslim|5|2161}}, {{hadith-usc|usc=no|muslim|5|2223}}</ref> The [[Sunnah|sunna]] also describes God's punishment for those who refuse or fail to pay zakat.<ref>{{hadith-usc|usc=yes|Bukhari|2|24|486}}</ref> On the [[Qiyama|day of Judgment]], those who did not give the zakat will be held accountable and punished.<ref name=Zysow>A. Zysow, "Zakāt." ''Encyclopaedia of Islam, Second Edition''.</ref>

The hadith contain advice on the state-authorized collection of the zakat. The collectors are required not to take more than what is due, and those who are paying the zakat are asked not to evade payment. The hadith also warn of punishment for those who take zakat when they are not eligible to receive it (see [[Zakat#Distribution|Distribution]] below).<ref name=Zysow/>

===Amount===
{{main|Calculation of Zakāt}}
The amount of zakat to be paid by an individual depends on the amount of money and the type of assets the individual possesses. The Quran does not provide specific guidelines on which types of wealth are taxable under the ''zakat'', nor does it specify percentages to be given. But the customary practice is that the amount of zakat paid on [[Financial capital|capital assets]] (e.g. money) is 2.5% (1/40).<ref name=AhmedGianci>Medani Ahmed and Sebastian Gianci, ''Zakat'', Encyclopedia of Taxation and Tax Policy,  p. 479-481</ref> Zakat is additionally payable on [[Agriculture|agricultural]] goods, [[precious metal]]s, [[mineral]]s, and [[livestock]] at a rate varying between 2.5% and 20% (1/5), depending on the type of goods.<ref>{{cite book |author= Kuran, Timur |chapter= The Economic Impact of Islamic Fundamentalism |editor1=Marty |editor2=Martin E. |editor3= Appleby, R. Scott |title= Fundamentalisms and the state: remaking polities, economies, and militance |publisher= University of Chicago Press |year=1996 |isbn=978-0-226-50884-9 |page=318 |url= https://books.google.com/books?id=doCmVaOnh_wC&pg=PA318}}</ref><ref>{{cite book|author=Kuran, Timur|title=Islam and Mammon: The Economic Predicaments of Islamism|publisher=Princeton University Press|year=2010|isbn=978-1-4008-3735-9|page=19|url=https://books.google.com/books?id=VkIJGPNzVIIC&pg=PA19}}</ref>

Zakat is usually payable on assets continuously owned over one lunar year that are in excess of the ''nisab'', a minimum monetary value.<ref>Scott, J. C. (1987), Resistance without protest and without organization: peasant opposition to the Islamic Zakat and the Christian Tithe, Comparative studies in society and history, 29(03), 417–452</ref> However, Islamic scholars have disagreed on this issue. For example, [[Abu Hanifa]] did not regard the nisab limit to be a pre-requisite for zakat, in the case of land crops, fruits and minerals.<ref>Yusuf al-Qaradawi (1999), Monzer Kahf (transl., Fiqh az-Zakat, Dar al Taqwa, London, [http://monzer.kahf.com/books/english/fiqhalzakah_vol1.pdf Volume 1] and [http://monzer.kahf.com/books/english/fiqhalzakah_vol2.pdf Volume 2]</ref> Other differences between Islamic scholars on zakat and nisab is acknowledged as follows by Yusuf al-Qaradawi,<ref name=yaqaradawi/>

<blockquote>Unlike prayers, we observe that even the ratio, the exemption, the kinds of wealth that are zakatable are subject to differences among scholars. Such differences have serious implications for Muslims at large when it comes to their application of the Islamic obligation of zakah. For example, some scholars consider the wealth of children and insane individuals zakatable, others don't. Some scholars consider all agricultural products zakatable, others restrict zakah to specific kinds only. Some consider debts zakatable, others don't. Similar differences exist for business assets and women's jewelry. Some require certain minimum (nisab) for zakatability, some don't. etc. The same kind of differences also exist about the disbursement of zakat.<br> – Shiekh Mahmud Shaltut<ref name=yaqaradawi>Yusuf al-Qaradawi (1999), Monzer Kahf (transl.) King Abdulaziz University, Saudi Arabia, [http://monzer.kahf.com/books/english/fiqhalzakah_vol1.pdf Fiqh az-Zakat, Volume 1], Dar al Taqwa, London, ISBN 978-967-5062-766, pp. xxi–xxii</ref></blockquote>

===Failure to pay===
[[File:Slot at the Zaouia Moulay Idriss II 1.jpg|thumb|A slot for giving zakat at the [[Zaouia Moulay Idriss II]] in [[Fez, Morocco]]<ref>{{cite book | url=https://books.google.com/books?id=2AtvBAAAQBAJ | title=Muhammad in History, Thought, and Culture: An Encyclopedia of the Prophet of God | year=2014 | pages=94 | isbn=978-1-61069-177-2 | last=Fitzpatrick | first=Coeli | last2=Walker | first2=Adam Hani}}</ref>]]
Some classical jurists have held the view that any Muslim who consciously refuses to pay zakat is an apostate, since the failure to believe that it is a religious duty (''fard'') is a form of unbelief (''kufr''), and should be killed.<ref>Abdullahi Ahmed An-Na'im Na (2010), ''Islam and the Secular State: Negotiating the Future of Shari`a'', Harvard University Press, ISBN 978-0674034563, pp. 58–63</ref><ref>Koylu, Mustafa (2003), ''Islam and its Quest for Peace: Jihad, Justice and Education'', ISBN 978-1565181809, pp. 88–89</ref><ref name="Aghnides205">{{Cite book|author=Nicolas Prodromou Aghnides|title =Mohammedan Theories of Finance, Volume 70|year=1916|publisher =Columbia university|url=https://books.google.com/books?id=IAVDAAAAIAAJ&pg=PA205|pages=205}}</ref> However, prevailing opinion among classical jurists prescribed sanctions such as fines, imprisonment or corporal punishment.<ref name="Aghnides">{{Cite book|author=Nicolas Prodromou Aghnides|title =Mohammedan Theories of Finance, Volume 70|year=1916|publisher =Columbia university|url=https://books.google.com/books?id=IAVDAAAAIAAJ&pg=PA302|pages=302–304}}</ref> Additionally, those who failed to pay the zakat would face God's punishment in the afterlife on the day of Judgment.<ref name=Zysow/>

The consequence of failure to pay zakat has been a subject of extensive legal debate, particularly when a Muslim is willing to pay zakat but refuses to pay it to a certain group or the state.<ref name="Aghnides"/><ref>{{cite book|author=Yusuf al-Qaradawi|authorlink=Yusuf al-Qaradawi|title=Fiqh Al-Zakāh: A Comprehensive Study of Zakah Regulations and Philosophy in the Light of the Qurʼan and Sunna|url=https://books.google.com/books?id=jF5by_O_QIEC&pg=PA40|accessdate=4 February 2016|year=2011|publisher=Islamic Book Trust in affiliation with The Other Press|isbn=978-967-5062-76-6|pages=40–41}}</ref> According to classical jurists, if the collector is unjust in the collection of zakat but just in its distribution, the concealment of property from him is allowed.<ref name="Aghnides"/> If, on the other hand, the collector is just in the collection but unjust in the distribution, the concealment of property from him is an obligation (''wajib'').<ref name="Aghnides"/> Furthermore, if the zakat is concealed from a just collector because the property owner wanted to pay his zakat to the poor himself, they held that he should not be punished for it.<ref name="Aghnides"/> If collection of zakat by force was not possible, use of military force to extract it was seen as justified, as was done by [[Abu Bakr]] during the [[Ridda Wars]], on the argument that refusing to submit to just orders is a form of treason.<ref name="Aghnides"/> However, Abu Hanifa, the founder of the [[Hanafi]] school, disapproved of fighting when the property owners undertake to distribute the zakat to the poor themselves.<ref name="Aghnides"/>

Some classical and contemporary scholars such as [[Ishaq Ibn Rahwayh]] and Yusuf al-Qaradawi have stated that the person who fails to pay Zakat should have the payment taken from them, along with half of his wealth.<ref>{{Cite web|title = Ruling on one who does not pay zakaah - islamqa.info|url = http://islamqa.info/en/93701|website = islamqa.info|accessdate = 2015-09-29}}</ref><ref>{{Cite book|title = Fiquh of Zakat Volume 1|last = Yusuf|first = Al Qardawi|publisher = King Abdul Aziz University Center for Research in Islamic Economics|year = 1984|location = Kingdom of Saudi Arabia|pages = 19}}</ref>

In modern states where zakat payment is compulsory, failure to pay is regulated by state law similarly to tax evasion.{{Citation needed|date=January 2017}}

===Distribution===
[[File:Waiting For Zakat (2393257046).jpg|thumb|Recipients waiting to receive zakat in India.]]
According to the Quran's Surah Al-Tawba, there are eight categories of people (''asnaf'') who qualify to benefit from ''zakat'' funds.<ref name=mariff>{{cite book|author=Ariff, Mohamed|title=The Islamic voluntary sector in Southeast Asia: Islam and the economic development of Southeast Asia|publisher=Institute of Southeast Asian Studies|year=1991|isbn=981-3016-07-8|url=https://books.google.com/books?id=NP4ZL0TJ9s4C&pg=PA38|page=38}}</ref>

{{quotation|“Alms are for the poor and the needy, and those employed to administer the (funds); for those whose hearts have been (recently) reconciled (to Truth); for those in bondage and in debt; in the cause of Allah; and for the wayfarer: (thus is it) ordained by Allah, and Allah is full of knowledge and wisdom.”| Qur'an, Sura 9 (Al-Tawba), [[Ayah|ayat]] 60<ref name="cite quran|9|60|s=ns">{{cite quran|9|60|s=ns}}</ref>}}

Scholars have traditionally interpreted this verse as identifying the following eight categories of Muslim causes to be the proper recipients of zakat:<ref name=mams/><ref name=fvbb>{{cite book|author=Benda-Beckmann, Franz von|title=Social security between past and future: Ambonese networks of care and support|publisher=LIT Verlag, Münster|year=2007|isbn=978-3-8258-0718-4|page=167}}</ref>

# Those living without means of livelihood (''Al-Fuqarā'''),<ref name=mams>{{cite book|author=M.A. Mohamed Salih (Editor: Alexander De Waal)|title=Islamism and its enemies in the Horn of Africa|publisher=Indiana University Press|year=2004|isbn=978-0-253-34403-8|pages=148–149|url=https://books.google.com/books?id=WYLSKQa9tHEC&pg=PA148}}</ref> the poor<ref name=fvbb/>
# Those who cannot meet their basic needs (''Al-Masākīn''),<ref name=mams/> the needy<ref name=fvbb/>
# To zakat collectors (''Al-Āmilīyn 'Alihā'')<ref name=mams/><ref name=fvbb/>
# To persuade those sympathetic to or expected to convert to Islam (''Al-Mu'allafatu Qulūbuhum''),<ref name=mams/> recent converts to Islam,<ref name=mariff/><ref name=fvbb/><ref name="Weiss, Anita M. 1986 80">{{cite book|author=Weiss, Anita M.|title=Islamic reassertion in Pakistan: the application of Islamic laws in a modern state|publisher=Syracuse University Press|year=1986|isbn=978-0-8156-2375-5|page=80|url=https://books.google.com/books?id=ROJZ5yt6O94C&pg=PA80}}</ref> and potential allies in the cause of Islam<ref name=fvbb/><ref name=twj/>
# To free from [[slavery]] or servitude (''Fir-Riqāb''),<ref name=mams/> slaves of Muslims who have or intend to free from their master by means of a ''kitabah'' contract<ref name=fvbb/><ref name=twj/>
# Those who have incurred overwhelming debts while attempting to satisfy their basic needs (''Al-Ghārimīn''),<ref name=mams/> debtors who in pursuit of a worthy goal incurred a debt<ref name=fvbb/>
# Those fighting for a religious cause or a cause of God (''[[Fi sabilillah|Fī Sabīlillāh]]''),<ref name=mams/> or for [[Jihad]] in the way of Allah by means of pen, word, or sword,<ref>{{cite book|last=Jonsson |first=David |title=Islamic Economics and the Final Jihad |url=https://books.google.com/books?id=UcAcdx1NA34C&pg=PA245|date=May 2006 |publisher=Xulon Press |isbn=978-1-59781-980-0 |page=245}}</ref> or for Islamic warriors who fight against the unbelievers but are not salaried soldiers.<ref name=fvbb/><ref name=twj>Juynboll, T.W. ''Handleiding tot de Kennis van de Mohaamedaansche Wet volgens de Leer der Sjafiitische School'', 3rd Edition, Brill Academic, pp. 85–88</ref><ref name=RelianceoftheTraveller>{{cite web|url=http://islamicbulletin.org/free_downloads/resources/reliance2_complete2.pdf |title=Reliance of the Traveller |deadurl=yes |archiveurl=https://web.archive.org/web/20130317053833/http://islamicbulletin.org/free_downloads/resources/reliance2_complete2.pdf |archivedate=17 March 2013 }}</ref>{{rp|h8.17}}
# Wayfarers, stranded travellers (''Ibnu Al-Sabīl''),<ref name=mams/> travellers who are traveling with a worthy goal but cannot reach their destination without financial assistance<ref name=fvbb/><ref name=twj/>

Zakat should not be given to one's own parents, grandparents, children, grandchildren, spouses or the descendants of the Prophet Muhammad.<ref name="Visser-2009-p29" />

Neither the Quran nor the Hadiths specify the relative division of zakat into the above eight categories.<ref name=masahikotimur>Masahiko Aoki, Timur Kuran and Gérard Roland (2012), Political consequences of the Middle East's Islamic economic legacy, in Institutions and Comparative Economic Development, Palgrave Macmillan, ISBN 978-1137034038, Chapter 5, pp. 124–148</ref> According to the [[Reliance of the Traveller]], the [[Shafi'i]] school requires zakat is to be distributed equally among the eight categories of recipients, while the [[Hanafi]] school permits zakat to be distributed to all the categories, some of them, or just one of them.<ref name = RelianceoftheTraveller />{{rp|h8.7}} Classical [[schools of Islamic law]], including [[Shafi'i]], are unanimous that collectors of zakat are to be paid first, with the balance to be distributed equally amongst the remaining seven categories of recipients, even in cases where one group’s need is more demanding.<ref>{{cite web|url=http://idosi.org/mejsr/mejsr12(2)12/9.pdf |title=Classical Jurists' View on the Allocation of Zakat: Is Zakat Investment Allowed? |author=Mohamad, Shamsiah |page=197|date=2012|work=Middle-East Journal of Scientific Research | issn=1990-9233 |accessdate=25 February 2015}}</ref>

Muslim scholars disagree whether zakat recipients can include non-Muslims. Islamic scholarship, historically, has taught that only Muslims can be recipients of zakat.<ref>{{cite journal|author=Benthal, Jonathan |url=https://openaccess.leidenuniv.nl/bitstream/handle/1887/16762/ISIM_1_The_Qur-an-s_Call_to_Alms_Zakat_the_Muslim_Tradition_of_Alms-giving.pdf?sequence=1 |title=The Qur'an's Call to Alms Zakat, the Muslim Tradition of Alms-giving|journal= ISIM Newsletter|volume= 98|issue=1|page= 13}}</ref> In recent times, some state that zakat may be paid to non-Muslims after the needs of Muslims have been met, finding nothing in the Quran or sunna to indicate that zakat should be paid to Muslims only.<ref name="Visser-2009-p29">{{cite book|author1=Visse|author2=Hans|author3=Visser, Herschel|title=Islamic finance: principles and practice|publisher=Edward Elgar Publishing|year=2009|isbn=978-1-84542-525-8|page=29|url=https://books.google.com/books?id=KIXe3rY_OkgC&pg=PA29}}</ref>

Additionally, the zakat funds may be spent on the administration of a centralized zakat collection system.<ref name=AhmedGianci/> Representatives of the [[Salafi movement]] include propagation of Islam and any struggle in righteous cause among permissible ways of spending, while others argue that zakat funds should be spent on social welfare and economic development projects, or science and technology education.<ref name="Visser-2009-p29"/> Some hold spending them for defense to be permissible if a Muslim country is under attack.<ref name="Visser-2009-p29"/> Also, it is forbidden to disburse zakat funds into investments instead of being given to one of the above eight categories of recipients.{{citation needed|date=December 2015}}

===Role in society===
The ''zakat'' is considered by Muslims to be an act of piety through which one expresses concern for the well-being of fellow Muslims,<ref name="Weiss, Anita M. 1986 80"/> as well as preserving social harmony between the wealthy and the poor.<ref>{{cite book|author=Scott, James C.|title=Weapons of the weak: everyday forms of peasant resistance|publisher=Yale University Press|year=1985|isbn=978-0-300-03641-1|page=171|url=https://books.google.com/books?id=THCcW1gCe_QC&pg=PA171}}</ref> ''Zakat'' promotes a more equitable redistribution of wealth and fosters a sense of solidarity amongst members of the ''[[Ummah]]''.<ref>{{Cite book|author=Jawad, Rana|title=Social welfare and religion in the Middle East: a Lebanese perspective|publisher=The Policy Press|year=2009|isbn=978-1-86134-953-8|page=60|url=https://books.google.com/books?id=-NXbIU5KwUgC&pg=PA60}}</ref>

==Historical practice==
{{Taxation in the Ottoman Empire sidebar}}

''Zakat'', an Islamic practice initiated by the [[Islamic prophet]] [[Muhammad]], has played an important role throughout its history.<ref name="Weiss-1986-p81">{{cite book|author=Weiss, Anita M.|title=Islamic reassertion in Pakistan: the application of Islamic laws in a modern state|publisher=Syracuse University Press|year=1986|isbn=978-0-8156-2375-5|page=81|url=https://books.google.com/books?id=ROJZ5yt6O94C&pg=PA81}}</ref> Schact suggests that the idea of zakat may have entered Islam from Judaism, with roots in the Hebrew and Aramaic word ''zakut''.<ref name=Heck/><ref name=yaqara/> However, some Islamic scholars<ref name=yaqara>Yusuf al-Qaradawi (1999), Monzer Kahf (transl.), Fiqh az-Zakat, Dar al Taqwa, London, Volume 1, ISBN 978-967-5062-766, pp. XXXIX–XL</ref> disagree that the Qur'anic verses on zakat (or zakah) have roots in Judaism.<ref>See the discussion about Children of Israel in verses {{cite quran|9|60|end=66|s=nosup}}</ref>

The [[caliph]] [[Abu Bakr]], believed by [[Sunni]] Muslims to be Muhammad's successor, was the first to institute a statutory ''zakat'' system.<ref>{{cite book|editor=Hawting, Gerald R.|title=The development of Islamic ritual|publisher=Ashgate Publishing|year=2006|isbn=978-0-86078-712-9|page=301|url=https://books.google.com/books?id=oCvf76uT3wMC&pg=PA301}}</ref> Abu Bakr established the principle that the zakat must be paid to the legitimate representative of the Prophet's authority, himself.<ref name="Weiss-1986-p81"/> Other Muslims disagreed and refused to pay zakat to Abu Bakr, leading to accusations of [[apostasy]] and, ultimately, the [[Ridda wars]].<ref name=mbonner15>Bonner, Michael (2003), ''Poverty and Charity in Middle Eastern Contexts'', State University of New York Press, ISBN 978-0791457382, p. 15: "In the old Arabic narratives about the early Muslim community and its conquests and quarrels, zakat and sadaqa loom large at several moments of crisis. These include the beginning of Muhammad’s prophetical career in Mecca, when what appear to be the earliest pieces of scripture insist on almsgiving more than any other human activity. These moments of crisis also include the wars of the ridda or apostasy in C.E. 632–634, just after Muhammad’s death. At that time most of the Arabs throughout the peninsula refused to continue paying zakat (now a kind of tax) to the central authority in Medina; Abu Bakr, upon assuming the leadership, swore he would force them all to pay this zakat, “even if they refuse me only a [camel’s] hobble of it,” and sent armies that subdued these rebels or “apostates” in large-scale battles that were soon followed by the great Islamic conquests beyond the Arabian peninsula itself."</ref><ref name="Weiss-1986-p81"/><ref>{{cite journal|author=Turner, Bryan |year=2007|title= Religious authority and the new media|journal= Theory, Culture & Society|volume= 24|issue=2|pages= 117–134|doi=10.1177/0263276407075001}}</ref>

The second and third caliphs, [[Umar bin Al-Khattab]] and [[Usman ibn Affan]], continued Abu Bakr's codification of the zakat.<ref name="Weiss-1986-p81"/> Uthman also modified the ''zakat'' collection protocol by decreeing that only "apparent" wealth was taxable, which had the effect of limiting ''zakat'' to mostly being paid on agricultural land and produce.<ref>{{Cite book|author=Hashmi, Sohail H.|chapter=The Problem of Poverty in Islamic Ethics|editor1=Galston|editor2=William A.| editor3=Hoffenberg, Peter H.|title=Poverty and Morality: Religious and Secular Perspectives|publisher=Cambridge University Press|year=2010|isbn=978-0-521-12734-9|page=202|url=https://books.google.com/books?id=VyzuGet8080C&pg=PA202}}</ref> During the reign of [[Ali ibn Abu Talib]], the issue of zakat was tied to legitimacy of his government. After Ali, his supporters refused to pay the zakat to [[Muawiyah I]], as they did not recognize his legitimacy.<ref name="Weiss-1986-p81"/>

The practice of Islamic state-administered ''zakat'' was short-lived in Medina. During the reign of [[Umar bin Abdul Aziz]] (717–720 A.D.), it is reported that no one in Medina needed the zakat. After him, zakat came to be considered more of an individual responsibility.<ref name="Weiss-1986-p81" /> This view changed over Islamic history. Sunni Muslims and rulers, for example, considered collection and disbursement of zakat as one of the functions of an Islamic state; this view has continued in modern Islamic countries.<ref>Faiz Mohammad (1991), [http://www.jstor.org/stable/41259525 Prospects of Poverty Eradication Through the Existing "Zakat" System in Pakistan], The Pakistan Development Review, Vol. 30, No. 4, 1119–1129</ref>

Zakat is one of the five pillars of Islam, and in various Islamic polities of the past was expected to be paid by all practicing Muslims who have the financial means (''[[nisab]]'').<ref>{{cite book|author=Tamimi, Azzam|title=Rachid Ghannouchi: a democrat within Islamism|publisher=Oxford University Press|year=2001|isbn=978-0-19-514000-2|page=140|url=https://books.google.com/books?id=b6GhV3Eu5OAC&pg=PA140}}</ref> In addition to their ''zakat'' obligations, Muslims were encouraged to make voluntary contributions (''[[sadaqat]]'').<ref>{{cite book|author=Bogle, Emory C.|title=Islam: origin and belief|publisher=University of Texas Press|year=1998|isbn=978-0-292-70862-4|page=31|url=https://books.google.com/books?id=IpFhLDUw20gC&pg=PA31}}</ref> The ''zakat'' was not collected from non-Muslims, although they were required to pay the ''[[jizyah]]'' tax.<ref>{{cite book|author=Khatab, Sayed|title=The power of sovereignty: the political and ideological philosophy of Sayyid Qutb|publisher=Taylor & Francis|year=2006|isbn=978-0-415-37250-3|page=62|url=https://books.google.com/books?id=MMjwuRh_2EkC&pg=PA62}}</ref><ref>{{cite book|author=Zaman, M. Raquibuz|chapter=Islamic Perspectives on Territorial Boundaries and Autonomy|editor1=Miller, David|editor2=Hashmi, Sohail H.|title=Boundaries and justice: diverse ethical perspectives|publisher=Princeton University Press|year=2001|isbn=978-0-691-08800-6|page=189|url=https://books.google.com/books?id=1vaCRnHK65kC&pg=PA189}}</ref> Depending on the region, the dominant portion of zakat went typically to ''Amil'' (the zakat collectors) or Sabīlillāh (those fighting for religious cause, the caretaker of local mosque, or those working in the cause of God such as proselytizing non-Muslims to convert to Islam).<ref name=masahikotimur/><ref name=marty321/>

==Contemporary practice==
According to researcher Russell Powell, as of 2010, Zakat was mandatory by state law in Libya, Malaysia, [[Zakat Council|Pakistan]], Saudi Arabia, Sudan, and Yemen. There were government-run voluntary Zakat contribution programs in Bahrain, Bangladesh, Egypt, Indonesia, Iran, Jordan, Kuwait, Lebanon, and the United Arab Emirates.<ref name=MJ>{{cite web|title=Zakat by country|url=https://moneyjihad.wordpress.com/2010/08/09/zakat-by-country/|website=Money Jihad|accessdate=9 April 2015|date=August 9, 2010}}</ref><ref name=Powell>{{cite journal|last1=Powell|first1=Russell|title=Zakat: Drawing Insights for Legal Theory and Economic Policy from Islamic Jurisprudence|journal=University of Pittsburgh Tax Review|date=2009|volume=7|issue=43|ssrn=1351024|accessdate=}}</ref>

===Collection===
Today, in most Muslim countries, zakat is at the discretion of Muslims over how and whether to pay, typically enforced by peer pressure, fear of God, and an individual's personal feelings.<ref name="Marty-1996-p.320" /> Among the Sunni Muslims, zakat committees are established, linked to a religious cause or local mosque, which collect zakat.<ref name="Clark">{{cite book|author=Clark, Janine A.|title=Islam, charity, and activism: middle-class networks and social welfare in Egypt, Jordan, and Yemen|publisher=Indiana University Press|year=2004|isbn=978-0-253-34306-2|page=153|url=https://books.google.com/books?id=-11yRIVUsa4C&pg=PA153}}</ref> Among the Shia Muslims, deputies on behalf of Imams collect the zakat.<ref name=naserg/>

In six of the 47 Muslim-majority countries—Libya, Malaysia, Pakistan, Saudi Arabia, Sudan and Yemen—zakat is obligatory and collected by the state.<ref name="Marty-1996-p.320">{{cite book|author1=Marty, Martin E. |author2=Appleby, R. Scott |lastauthoramp=yes |title=Fundamentalisms and the state: remaking polities, economies, and militance|publisher=University of Chicago Press|year=1996|isbn=978-0-226-50884-9|page=320|url=https://books.google.com/books?id=doCmVaOnh_wC&pg=PA320}}</ref><ref name=Hasan>{{cite book|author=Samiul Hasan|title=Human Security and Philanthropy: Islamic Perspectives and Muslim Majority Country Practices|publisher=Springer|year=2015|page=130|url=https://books.google.com/books?id=-JVwCAAAQBAJ&pg=PA130}}</ref><ref name=Behdad-Nomani>{{cite book|author1=Sohrab Behdad|author2=Farhad Nomani|title=Islam and the moral economy: the challenge of capitalism|publisher=Routledge|year=2006|page=268|url=https://books.google.com/books?id=QQWAAgAAQBAJ&pg=PT268}}</ref><ref>{{cite book|author=Tripp, Charles|title=Islam and the Everyday World: Public Policy Dilemmas|publisher=Cambridge University Press|year=2006|isbn=978-0-521-86377-3|page=125|url=https://books.google.com/books?id=hFhyZ28it0AC&pg=PA125}}</ref> In [[Jordan]], [[Bahrain]], [[Kuwait]], [[Lebanon]], and [[Bangladesh]], the ''zakat'' is regulated by the state, but contributions are voluntary.<ref>{{cite book|author=Kogelmann, Franz|chapter=Sidi Fredj: A Case Study of a Religious Endowment in Morocco under the French Protectorate|editor=Weiss, Holger|title=Social welfare in Muslim societies in Africa|publisher=Nordic Africa Institute|year=2002|isbn=978-91-7106-481-3|page=68|url=https://books.google.com/books?id=-JcYwpJJs8oC&pg=PA68}}</ref>

The states where zakat is compulsory differ in their definition of the base for zakat computation.<ref name=Behdad-Nomani/> Zakat is generally levied on livestock (except in Pakistan) and agricultural produce, although the types of taxable livestock and produce differ from country to country.<ref name=Behdad-Nomani/> Zakat is imposed on cash and precious metals in four countries with different methods of assessment.<ref name=Behdad-Nomani/> Income is subject to zakat in Saudi Arabia and Malaysia, while only Sudan imposes zakat on "wealth that yields income".<ref name=Behdad-Nomani/> In Pakistan, property is exempt from the zakat calculation basis, and the compulsory zakat is primarily collected from the agriculture sector.<ref name=marty321>{{cite book|author1=Marty, Martin E.  |author2=Appleby, R. Scott |lastauthoramp=yes |title=Fundamentalisms and the state: remaking polities, economies, and militance|publisher=University of Chicago Press|year=1996|isbn=978-0-226-50884-9|pages=320–321 |url=https://books.google.com/books?id=doCmVaOnh_wC&pg=PA320}}</ref>

Under compulsory systems of zakat tax collection, such as Malaysia and Pakistan, evasion is very common and the alms tax is [[regressive tax|regressive]].<ref name="Marty-1996-p.320" /> A considerable number of Muslims accept their duty to pay zakat, but deny that the state has a right to levy it, and they may pay zakat voluntarily while evading official collection.<ref name=Behdad-Nomani/> In discretion-based systems of collection, studies suggest zakat is collected from and paid only by a fraction of Muslim population who can pay.<ref name="Marty-1996-p.320" />

In the United Kingdom, which has a Muslim minority, more than three out of ten Muslims gave to charity (Zakat being described as "the Muslim practice of charitable donations"), according to a 2013 poll of 4000 people.<ref name=nbc>{{cite news|url=http://worldnews.nbcnews.com/_news/2013/07/22/19611201-muslims-give-more-to-charity-than-others-uk-poll-says?lite|title=Muslims give more to charity than others, UK poll says|publisher=nbcnews.com|date=22 July 2013|accessdate=29 July 2013}}</ref> According to the [[Self-report study|self-reported poll]], British Muslims, on average, gave US$567 to charity in 2013, compared to $412 for [[Jew]]s, $308 for [[Protestant]]s, $272 for [[Catholic]]s and $177 for [[atheist]]s.<ref name=nbc/>

===Distribution===
The primary sources of sharia also do not specify to whom the zakat should be paid{{snd}} to zakat collectors claiming to represent one class of zakat beneficiary (for example, poor), collectors who were representing religious bodies, or collectors representing the Islamic state.<ref name=masahikotimur/><ref>Lessy, Z. (2009), Zakat (Alms-Giving) Management In Indonesia: Whose Job Should It Be?, La Riba Journal of Islamic Economy, 3(1), pp. 155–175</ref> This has caused significant conflicts and allegations of zakat abuse within the Islamic community, both historically<ref name=masahikotimur/> and in modern times.<ref>A.H. bin Mohd Noor (2011), Non recipients of zakat funds (NRZF) and its impact on the performance of zakat institution: A conceptual model, in Humanities, Science and Engineering (CHUSER), 2011 IEEE Colloquium, ISBN 978-1-4673-0021-6, pp. 568–573</ref>

''Fi Sabillillah'' is the most prominent ''asnaf'' in Southeast Asian Muslim societies, where it broadly construed to include funding missionary work, Quranic schools and anything else that serves the Islamic community (''ummah'') in general.<ref>{{cite book|author=Ariff, Mohamed|title=The Islamic voluntary sector in Southeast Asia: Islam and the economic development of Southeast Asia|publisher=Institute of Southeast Asian Studies|year=1991|isbn=981-3016-07-8|url=https://books.google.com/books?id=NP4ZL0TJ9s4C&pg=PA39|page=39}}</ref>

===Role in society===
In 2012, Islamic financial analysts estimated annual zakat spending exceeded US$200 billion per year, which they estimated at 15 times global humanitarian aid contributions.<ref name="irinnews.org">{{cite web|url=http://www.irinnews.org/Report/95564/Analysis-A-faith-based-aid-revolution-in-the-Muslim-world|title=Analysis: A faith-based aid revolution in the Muslim world?|publisher=irinnews.org|accessdate=2012-12-02|date=2012-06-01}}</ref><ref>However that same year the National Center for Charitable Statistics reported that "individual" charitable giving in one non-Muslim country amounted to $228.93 billion (source: {{cite web|url=http://nccs.urban.org/nccs/statistics/Charitable-Giving-in-America-Some-Facts-and-Figures.cfm |title=Charitable Giving in America: Some Facts and Figures|year=2012|accessdate=8 April 2015}})</ref> Islamic scholars and development workers state that much of this zakat practice is mismanaged, wasted or ineffective.<ref name="irinnews.org"/> About a quarter of the Muslim world<ref>about 400 million people</ref> continues to live on $1.25 a day or less, according to the 2012 report.<ref name="irinnews.org"/>

A 1999 study of Sudan and Pakistan, where zakat is mandated by the state, estimated that zakat proceeds ranged between 0.3 and 0.5 percent of GDP, while a more recent report put zakat proceeds in Malaysia at 0.1% of GDP.<ref name=Behdad-Nomani/> These numbers are far below what was expected when the governments of these countries tried to Islamize their economies, and the collected amount is too small to have a sizeable macroeconomic effect.<ref name=Behdad-Nomani/>

In a 2014 study,<ref name=zakatwaqf/> Nasim Shirazi states widespread poverty persists in Islamic world despite zakat collections every year. Over 70% of the Muslim population in most Muslim countries is impoverished and lives on less than US$2 per day. In over 10 Muslim-majority countries, over 50% of the population lived on less than $1.25 per day income, states Shiraz.<ref name=zakatwaqf/> In Indonesia{{snd}} the world's most populous and predominantly Muslim country{{snd}} 50% of Muslims live on less than $2 per day. This suggest large scale waste and mismanagement by those who collect and spend zakat funds. Given the widespread poverty among Muslim-majority countries, the impact of zakat in practice, despite the theoretical intent and its use for centuries, has been questioned by scholars.<ref>{{cite journal |author=Zeinelabdin, A. R. |year=1996 |journal=Journal of Economic Cooperation Among Islamic Countries |title=Poverty in OIC Countries: Status, Determinants and Agenda for Action |volume=17 |issue=3–4 |pages=1–40 |url=http://wavw.sesrtcic.org/files/article/53.pdf}}</ref> Zakat has so far failed to relieve large scale absolute poverty among Muslims in most Muslim countries.<ref name=zakatwaqf>{{cite journal|author=Shirazi, Nasim |date=May 2014|title= Integrating Zakāt and Waqf into the Poverty Reduction Strategy of the IDB Member Countries|journal=Islamic Economic Studies|volume= 22|issue = 1|pages=79–108}}</ref>

==Related terms==
Zakat is required of Muslims only. For non-Muslims living in an Islamic state, [[sharia]] was historically seen as mandating ''[[jizya]]'' (poll tax).<ref>Böwering, Gerhard, ed. (2013), ''The Princeton Encyclopedia of Islamic Political Thought'', Princeton University Press. p. 545</ref> Other forms of taxation on Muslims or non-Muslims, that have been used in Islamic history, include ''[[kharaj]]'' (land tax),<ref>Lewis, Bernard (2002), ''The Arabs in History'', Oxford: Oxford University Press, ISBN 0-19-280310-7, page 70-74</ref> ''[[khums]]'' (tax on booty and loot seized from non-Muslims, sudden wealth),<ref>Iqbal, Zafar and Lewis, Mervyn (2009) ''An Islamic Perspective on Governance'', ISBN 978-1847201386, pp. 99–115</ref> ''ushur'' (tax at state border, sea port, and each city border on goods movement, customs),<ref>Nienhaus, Volker (2006), ''Zakat, taxes and public finance in Islam, in Islam and the Everyday World: Public Policy Dilemmas''. Sohrab Behdad, Farhad Nomani (eds.), ISBN 978-0415368230, pp. 176–189</ref> ''kari'' (house tax)<ref>{{cite journal|author=Lambton, K.S. |title=An Account of the Tārīkhi Qumm|journal=Bulletin of the School of Oriental and African Studies|volume =12|issue =3–4|date= October 1948|pages=586–596|doi=10.1017/s0041977x00083154}}</ref> and ''chari'' (sometimes called ''maara'', pasture tax).<ref>{{cite journal|author=Hamid, S.|year=1995|title=Bookkeeping and accounting control systems in a tenth-century Muslim administrative office|journal=Accounting Business & Financial History|volume =5|issue =3|pages= 321–333|doi=10.1080/09585209500000049}}</ref><ref>Kulke, H. and Rothermund, D. (1998), ''A History of India'', 3rd Edition, Routledge, ISBN 0-415-15482-0, pp. 158–163</ref>

There are differences in the interpretation and scope of zakat and other related taxes in various sects of Islam. For example, ''[[khums]]'' is interpreted differently by [[Sunni]]s and [[Shi'ites]], with Shia expected to pay one fifth of their excess income after expenses as ''khums'', and Sunni don't.<ref>{{cite book|author=Momen, Moojan|title=An Introduction to Shi`i Islam: The History and Doctrines of Twelver Shi`ism | publisher=Yale University Press|year=1987|isbn=978-0-300-03531-5|page=179|url=https://books.google.com/books?id=B0OL5Z8S-V0C&pg=PA179}}</ref> At least a tenth part of ''zakat'' and ''khums'' every year, among Shi'ites, after its collection by Imam and his religious deputies under its doctrine of ''niyaba'', goes as income for its hierarchical system of Shia clergy.<ref name=naserg>Ghobadzadeh, Naser (2014), ''Religious Secularity: A Theological Challenge to the Islamic State'', Oxford University Press, ISBN 978-0199391172, pp. 193–195</ref><ref>Martin, Richard (2003) ''Encyclopedia of Islam & the Muslim World'', Macmillan Reference, ISBN 978-0028656038, pp. 274, 350–351</ref> Among [[Isma'ilism|Ismaili]] sub-sect of Shias, the mandatory taxes which includes zakat, is called ''dasond'', and 20% of the collected amount is set aside as income for the Imams.<ref>{{cite book|last1=Rose, Ebaugh and Cherry|title=Global Religious Movements Across Borders: Sacred Service|date=2014|publisher=Ashgate|isbn=978-1409456872|pages=149–150}}</ref> Some branches of Shia Islam treat the right to lead as Imam and right to receive 20% of collected zakat and other alms as a hereditary right of its clergy.

''Sadaqah'' is another related term for charity, usually construed as a discretionary counterpart to zakat.<ref name=MIC-145>{{cite book|editor1-last=Meri|editor1-first=Josef W.|title=Medieval Islamic Civilization: An Encyclopedia|publisher=Psychology Press.|page=145|url=https://books.google.com/books?id=H-k9oc9xsuAC&pg=PA145|isbn=9780415966900}}</ref>

===''Zakat al-Fitr''===
{{further|Zakat al-Fitr}}
''Zakat al-Fitr'' or ''Sadaqat al-Fitr''<ref name=Hidaya>{{cite web|title=Sadaqat-ul-Fitr|url=http://www.hidaya.org/social-welfare/sadaqat-ul-fitr/|website=Hidaya Foundation|accessdate=8 April 2015}}</ref> is another, smaller charitable obligation, mandatory for all Muslims — male or female, minor or adult as long as he/she has the means to do so — that is traditionally paid at the end of the [[fasting]] in the [[Islamic calendar|Islamic holy month]] of [[Ramadan]].<ref>{{cite journal|author=Kasule, O. H. |year=1986|title= Muslims in Trinidad and Tobago|journal= Journal Institute of Muslim Minority Affairs|volume= 7|issue=1|pages=195–213|doi=10.1080/13602008608715974}}</ref><ref name=mb2008/> The collected amount is used to pay the zakat collectors and to the poor Muslims so that they may be provided with a means to celebrate [[Eid ul-Fitr|`Eid al-Fitr]] (the [[festival]] of breaking the fast) following Ramadan, along with the rest of the Muslims.<ref>Al-Hamar, M., Dawson, R., & Guan, L. (2010), ''A culture of trust threatens security and privacy in Qatar'', IEEE 10th International Conference, ISBN 978-1-4244-7547-6, pp. 991–995</ref>

Zakat al-Fitr is a fixed amount assessed per person, while Zakat al mal is based on personal income and property.<ref name=mb2008>{{cite journal|author= Buehler, M.|year=2008|title= The rise of shari'a by-laws in Indonesian districts: An indication for changing patterns of power accumulation and political corruption|journal= South East Asia Research|volume= 16|issue=2|pages= 255–285|doi=10.5367/000000008785260473}}</ref> According to one source, the Hidaya Foundation, the suggested Zakat al Fitr donation is based on the price of 1 Saa (approx. 3&nbsp;kg) of rice or wheat at local costs, (as of 2015, approximately $7.00 in the U.S.).<ref name=Hidaya/>

==See also==
* [[Islamic economics]]
* [[Islamic socialism]]
* [[Islamic taxes]]
* [[Jizya]]
* [[Khums]]
* [[Kharaj]]
* [[Sadaqah]]
* [[Qard al-Hassan]]
* [[Zakat Council]] (Pakistan)
* [[Zakat al-fitr]], a different form of zakat which follows the pillar of [[Sawm]] (fasting in [[Ramadan]]).

Charity practices in other religions:
* [[Tithe]]
* [[Poor tithe]]
* [[Tzedakah]] ([[Judaism]])
* [[Maaser Ani]] (tithing in Judaism)
* [[Dāna]]

==References==
===Citations===
{{reflist|colwidth=30em}}

===Books and articles===
*P. Bearman ed. (2012). ''[[Encyclopaedia of Islam]], Second Edition''. Brill Online.
*Joseph J. Cordes, Robert D. Ebel, Jane Gravelle ed. (2005). ''Encyclopedia of Taxation and Tax Policy''. [[Urban Institute]]
*John L. Esposito ed. (2009). '[The Oxford Encyclopedia of the Islamic World''. [[Oxford University Press]].
*Hunter, Shireen; Malik, Huma; Senturk, Recep (2005). ''Islam and Human Rights: Advancing a U.S.-Muslim Dialogue''. [[Center for Strategic and International Studies]], 2005.

==Further reading==
*{{cite book|author=Mattson, Ingrid|chapter=Status-Based Definitions of Need in Early Islamic ''Zakat'' and Maintenance Laws|editor1=Michael Bonner|editor2=Mine Ener|editor3=Amy Singer|title=Poverty and charity in Middle Eastern contexts|publisher=SUNY Press|year=2003|isbn=978-0-7914-5737-5|url=https://books.google.com/books?id=zBp3y5lWz58C&pg=PA31}}
*{{cite book|author=Weiss, Holger|chapter=Zakāt and the Question of Social Welfare: An Introductory Essay on Islamic Economics and Its Implications for Social Welfare|editor=Weiss, Holger|title=Social welfare in Muslim societies in Africa|publisher=Nordic Africa Institute|year=2002|isbn=978-91-7106-481-3|url=https://books.google.com/books?id=-JcYwpJJs8oC&pg=PA7}}
*[http://monzer.kahf.com/books/english/fiqhalzakah_vol1.pdf Fiqh al Zakah (Vol. I)], Dr. [[Yusuf al-Qaradawi|Yusuf al Qardawi]]
*[http://zakat-publications.s3.amazonaws.com/2275/zakat-book.pdf The Zakat Handbook: A Practical Guide for Muslims in the West]
*[http://www.zakatchicago.org/ZakatBook.pdf The Institution of Zakat: An Obligation and an Opportunity] (2005) The Central Zakat Committee of The Council of Islamic Organizations of Greater Chicago

==External links==
*[http://shiatvonline.com/category/fiqh/furu-e-deen/zakat/ Shia Muslims view on Zakat]
*[http://www.zakatguide.org/english/Genaral_Rules_Calculating_Zakah.html Sunni Muslims view on Zakat Pages]
*[http://courses.arch.vt.edu/courses/wdunaway/gia5274/scott87.pdf Peasant opposition to the Islamic Zakat and the Christian Tithe], James Scott (1987), Journal: Comparative Studies in Society and History
*[http://digital.law.washington.edu/dspace-law/bitstream/handle/1773.1/634/15PacRimLPolyJ683.pdf THE INFLUENTIAL LEGACY OF DUTCH ISLAMIC POLICY ON THE FORMATION OF ZAKAT (ALMS) LAW IN MODERN INDONESIA], Arskal Salim (2006), Journal: Pacific Rim Law & Policy Review

{{Charity}}

{{Authority control}}

[[Category:Arabic words and phrases]]
[[Category:Zakat| ]]
[[Category:Taxation in Islam]]
